name: GotoPositionPlugin
version: 1.0
main: jp.ne.suehiro.GotoPositionPlugin
api-version: 1.20
commands:
  gotouser:
    description: Indicate the direction on the screen by specifying the user.
    usage: /gotouser <username>
  gotonamedobject:
    description: Display the direction of the object with the specified name on the screen.
    usage: /gotonamedobject <objectname>
  gotoposition:
    description: Display the direction of the specified coordinates on the screen.
    usage: /gotoposition <x> <z>
